In [1]:
import pandas as pd

original_data = pd.read_csv('./xenonpy_input.csv')
original_data['Mn'] = original_data['Mn'] + original_data['Mn_2']
original_data['Sn'] = original_data['Sn'] + original_data['Sn_2']
original_data.drop(columns=['Mn_2', 'Sn_2'], inplace=True)
original_data

,Mn,Fe,Cr,Sn,Cu,Ge,Ga,Zn,Nb,Si,Ag,Re,Ni,Sb,N,C,B
0,2.70,0.10,0.15,0.75,0.00,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.75,0.20,0.05
1,2.60,0.10,0.30,0.00,0.60,0.3,0.0,0.0,0.1,0.0,0.0,0.0,0.00,0.0,0.87,0.08,0.05
2,2.80,0.10,0.10,0.00,0.70,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.00,0.0,0.75,0.25,0.00
3,2.75,0.00,0.25,0.10,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.4,0.93,0.07,0.00
4,2.95,0.00,0.00,0.05,0.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.3,0.89,0.06,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132206,2.66,0.04,0.25,0.55,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.91,0.09,0.00
132207,2.75,0.00,0.20,0.05,0.50,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.00,0.00,0.00
132208,2.90,0.10,0.00,0.00,0.40,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.20,0.0,0.75,0.20,0.05
132209,2.74,0.06,0.15,0.05,0.45,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.15,0.0,0.95,0.00,0.05
132210,2.62,0.08,0.25,0.35,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.2,0.87,0.13,0.00

In [2]:
data = original_data.div(original_data.sum(axis=1), axis=0)*100
data

,Mn,Fe,Cr,Sn,Cu,Ge,Ga,Zn,Nb,Si,Ag,Re,Ni,Sb,N,C,B
0,54.0,2.0,3.0,15.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,4.0,1.0
1,52.0,2.0,6.0,0.0,12.0,6.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,17.4,1.6,1.0
2,56.0,2.0,2.0,0.0,14.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,15.0,5.0,0.0
3,55.0,0.0,5.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,18.6,1.4,0.0
4,59.0,0.0,0.0,1.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,17.8,1.2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132206,53.2,0.8,5.0,11.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.2,1.8,0.0
132207,55.0,0.0,4.0,1.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0
132208,58.0,2.0,0.0,0.0,8.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,15.0,4.0,1.0
132209,54.8,1.2,3.0,1.0,9.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,19.0,0.0,1.0
132210,52.4,1.6,5.0,7.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,17.4,2.6,0.0

In [3]:
def generat_formula(x):
    formula = ''
    for key, value in x.items():
        if key == 'formula':
            continue
        if value > 0:
            formula += f"{key}{round(value, 3)}"
    return formula
original_data['formula'] = data.apply(generat_formula, axis = 1)

In [5]:
original_data.to_csv('./xenonpy_input.csv', index=False)